---
title: "piulchm"
output: html_document
---


```{r}
install.packages("plotly")
library(plotly)
library(ggcorrplot)
```


```{r}
q= ggplot(data = p_values, aes(x=measure2, y=measure1, fill=pvalue)) + 
  geom_tile() +
  geom_text(aes(measure2, measure1, label = pvalue), size = 2) +
  scale_fill_gradient2(low = "blue", high = "red",
                       limit = c(0,1), name="pvalue") +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        panel.background = element_blank())

q + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

#####


#data_rangeled[upper.tri(data_rangeled, diag=FALSE)] <- NA

b = ggplot(data= data_rangeled3, aes(x=X1, y=X2, fill=value)) + 
  geom_tile() +
  geom_text(aes(X1, X2, label = value), size = 2) +
  scale_fill_gradient2(low = "red",high="white", midpoint = .75,
                       limit = c(0,1), name="pvalue", na.value = "white") +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        panel.background = element_blank())

b + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))


ggcorrplot(data_rangeled, hc.order = TRUE, type = "upper",
     outline.col = "white")


meltnew(data_rangeled) %>%
  ggplot(aes(X1, X2, fill = value)) + geom_tile() +
  geom_text(aes(label = value)) 


#another way to  get the lower tear 

meltnew(data_rangeled) %>%
  ggplot(aes(X1, X2, fill = value)) + geom_tile() +
  geom_text(aes(label = value), size=2)

```

